import Head from 'next/head';

import { Zebra } from '@/components/Zebra/Zebra';

import styles from '@/styles/Home.module.css';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div style={{ backgroundColor: 'white' }}>
          <Zebra colors={['#fddddd', '#fcf1f1']}>
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nostrum enim optio dolorum
            amet deleniti repudiandae aspernatur natus dolor unde inventore! Dicta vel beatae et
            atque sit possimus repellat laboriosam provident. Lorem ipsum, dolor sit amet
            consectetur adipisicing elit. Nostrum enim optio dolorum amet deleniti repudiandae
            aspernatur natus dolor unde inventore! Dicta vel beatae et atque sit possimus repellat
            laboriosam provident. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nostrum
            enim optio dolorum amet deleniti repudiandae aspernatur natus dolor unde inventore!
            Dicta vel beatae et atque sit possimus repellat laboriosam provident.
          </Zebra>
        </div>
      </main>
    </>
  );
}
